version: "3"

networks:
  db-net:
    driver: "bridge"
  blockchain-net:
    driver: "bridge"

services:

  mongo:
    image: mongo:latest
    networks:
      - db-net

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --account "${BLOCKCHAIN_ACCOUNT},1000000000000000000"
    networks:
      - blockchain-net

  blockcovid:
    build:
      context: .
    ports:
      - ${SERVER_PORT}:8091
    env_file:
      - .env
    depends_on:
      - mongo
      - ganache
    networks:
      - db-net
      - blockchain-net
