version: "3"

networks:
  db-net:
    driver: "bridge"
  blockchain-net:
    driver: "bridge"

services:

  mongo:
    image: mongo:latest
    networks:
      - db-net

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --account "0xb43436657ed0d6b922f3e7fab75dc32c610796d374daa6d7f1878669ff79d0e5,1000000000000000000"
    networks:
      - blockchain-net

  blockcovid:
    build:
      context: .
    ports:
      - "8091:8091"
    links:
      - mongo
      - ganache
    depends_on:
      - mongo
      - ganache
    networks:
      - db-net
      - blockchain-net
