name: Code Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Test coverage with Gradle
        run: ./gradlew test jacocoTestReport

      - uses: codecov/codecov-action@v1
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true